import { Injectable, UnauthorizedException, ConflictException, OnModuleInit } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, DataSource } from 'typeorm';
import * as bcrypt from 'bcrypt';
import { User } from './entities/user.entity';
import { RegisterDto } from './dto/register.dto';
import { LoginDto } from './dto/login.dto';

@Injectable()
export class AuthService implements OnModuleInit {
    constructor(
        @InjectRepository(User)
        private usersRepository: Repository<User>,
        private jwtService: JwtService,
        private dataSource: DataSource,
    ) { }

    async onModuleInit() {
        // Initialize User ID sequence to start at 1000000000
        try {
            // Check if we are using PostgreSQL
            if (this.dataSource.options.type === 'postgres') {
                // Check if sequence exists and current value
                // This is a bit hacky but works for dev. In prod, use migrations.
                await this.dataSource.query(`ALTER SEQUENCE users_id_seq RESTART WITH 1000000000;`);
                console.log('User ID sequence initialized to 1000000000');
            }
        } catch (e) {
            console.warn('Failed to initialize user ID sequence (might already be set or different DB):', e.message);
        }
    }

    async register(registerDto: RegisterDto) {
        const { username, password } = registerDto;

        // Check if user exists
        const existingUser = await this.usersRepository.findOne({ where: { username } });
        if (existingUser) {
            throw new ConflictException('Username already exists');
        }

        // Hash password
        const salt = await bcrypt.genSalt();
        const password_hash = await bcrypt.hash(password, salt);

        // Create user (ID is auto-generated by DB)
        const user = this.usersRepository.create({
            username,
            password_hash,
        });

        await this.usersRepository.save(user);

        // Generate token
        const payload = { username: user.username, sub: user.id };
        return {
            access_token: this.jwtService.sign(payload),
            user: {
                id: user.id,
                username: user.username
            }
        };
    }

    async login(loginDto: LoginDto) {
        const { username, password } = loginDto;
        const user = await this.usersRepository.findOne({ where: { username } });

        if (!user || !(await bcrypt.compare(password, user.password_hash))) {
            throw new UnauthorizedException('Invalid credentials');
        }

        const payload = { username: user.username, sub: user.id };
        return {
            access_token: this.jwtService.sign(payload),
            user: {
                id: user.id,
                username: user.username
            }
        };
    }
}
